const INVITADOS = [
  "Leonardo",
  "Davis",
  "steve",
  "Nicole",
  "Lucho",
  "Daniel",
  "Piero Alonso",
  "Andrea",
  "Gianella",
  "Samanta",
  "Juan",
  "Richard",
  "Dereck",
  "Adriana",
  "Yovana",
  "dylan",
  "jose luis",
  "Wilberto",
  "Jose Cabezas Esquen",
  "Socorro Esquen",
  "Maria Del Carmen",
  "juan david",
  "joaquin",
  "Pamela",
  "Jasumi",
  "Hans",
  "Erick Guarniz Ortega",
  "Alexis Chapoñan",
  "Luis Angel",
  "Aparcada",
  "Marcial",
  "leonela",
  "paul",
  "roy",
  "Jhonatan Saenz",
  "Juan Sánchez",
  "Marcial Medina Carrion",
  "Leonela Pajuelo Manrique",
  "José Armando",
  "Caleb",
  "Amir",
  "Chirinos",
  "jefrry",
  "Sergio",
  "Aaron Álvarez",
  "luisa",
  "fabiana",
  "Estefany Malqui Tarazona",
  "Kelly Malqui Tarazona",
  "Jean Malqui Tarazona",
  "Mirian Escobedo Aquino",
  "Estefany Escobedo Aquino",
  "Dylan",
  "Elvira Tarazona Ñaupari",
  "Norma Aquino Ñaupari",
  "Yajaira Chacon",
  "Jahayra amiga",
  "Alissa amiga",
  "Jovana",
  "Jessica Vasquez Alfaro",
  "Angie Vasquez Alfaro",
  "Jassir Vasquez Alfaro",
  "David Vasquez Hurtado",
  "Alex Vasquez Hurtado",
  "Alyssa",
  "Zixgner",
  "Benjamin Wong",
  "Ana Kassandra",
  "jeffry",
  "Mathew",
  "Henry",
  "Carlos",
  "daniela",
  "jazmin",
];

